/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AutoUpload: typeof import('./../src/components/AutoUpload.vue')['default']
    FormUpload: typeof import('./../src/components/FormUpload.vue')['default']
    ManualUpload: typeof import('./../src/components/ManualUpload.vue')['default']
  }
}
