/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IndexList: typeof import('./../src/components/index-list/index.vue')['default'];
    VirtualList: typeof import('./../src/components/VirtualList.vue')['default'];
  }
}
